//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka_uyg.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BankaEntities2 : DbContext
    {
        public BankaEntities2()
            : base("name=BankaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Havale> Havale { get; set; }
        public virtual DbSet<Hesaplar> Hesaplar { get; set; }
        public virtual DbSet<Hgs> Hgs { get; set; }
        public virtual DbSet<Kredi> Kredi { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Virman> Virman { get; set; }
    
        public virtual int SP_BILGILERIEKLE(string odemeTipi, Nullable<decimal> odemeTutarı, string musteriId)
        {
            var odemeTipiParameter = odemeTipi != null ?
                new ObjectParameter("OdemeTipi", odemeTipi) :
                new ObjectParameter("OdemeTipi", typeof(string));
    
            var odemeTutarıParameter = odemeTutarı.HasValue ?
                new ObjectParameter("OdemeTutarı", odemeTutarı) :
                new ObjectParameter("OdemeTutarı", typeof(decimal));
    
            var musteriIdParameter = musteriId != null ?
                new ObjectParameter("MusteriId", musteriId) :
                new ObjectParameter("MusteriId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BILGILERIEKLE", odemeTipiParameter, odemeTutarıParameter, musteriIdParameter);
        }
    }
}
